server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biubidang_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fw030425
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  accessKey: n2QoSgH1vHvW8KdqQj2fHwA71ePcHG4jUWuiTNkk
  secretKey: 5RI3UYB0r4M08nL1Xd8T0LZTex0Gcyzts1kNTGtm
  bucket: biubidang-blog-test
